challenge = "338263220324550944848275622387998953745003127460171535924720547159558905901"
context = "236047395000730791932746644905733468828822355073856266299183394260100537158"
cutoff_day = "17"
cutoff_month = "12"
cutoff_year = "2004"
dob_commit = "16022106584012173190491856643789125182732476915620570219636972390778935984781"
dob_day = "1"
dob_month = "1"
dob_year = "1990"
