"dob_year"= "1990"
"dob_month"= "1"
"dob_day"= "1"
"cutoff_year"= "2004"
"cutoff_month"= "12"
"cutoff_day"= "19"
"challenge"= "429679591172845115791987293013123918984842808275900670360616035180626942823"
"context"= "236047395000730791932746644905733468828822355073856266299183394260100537158"
"dob_commit"= "16022106584012173190491856643789125182732476915620570219636972390778935984781"
"active_root"= "14642879328198360177391514109182144397362467512971976506013820920878525844554"
"active_leaf"= "16022106584012173190491856643789125182732476915620570219636972390778935984781"
"active_path"= [
        "0",
        "5151499478991301833156025595048985053689893395646836724335623777508747990769",
        "6425444215191838285069835781607981895589384041954338275956759438530131468944",
        "15366428887851194658173001994030115403889500460316803633813719685335613213216",
        "16035753591704748209377180686147291356460509756602580601938195381349806255502",
        "8144004172175511637373287007127031310278744323254585308703615193240287509983",
        "796074195456137668475057404256202455048248910468542119987582633322559749494",
        "20567739078944838550556895816409602128127282297589578747131836752205066334747"
    ]
"active_index"= "0"